- name: Install apt packages
  become: yes
  apt:
    # * apptitude is required to execute apt: upgrade later.
    #   https://github.com/ansible/ansible/issues/16884#issuecomment-278138707
    # * ruby-dev is required to install jekyll.
    # * python-setuptools is necessary to use Ansible pip rules.
    #   https://stackoverflow.com/questions/52901272/
    name: ['aptitude', 'clang', 'curl', 'emacs', 'gcc', 'git', 'llvm-dev', 'maven', 'mercurial', 'python3', 'python3-pip', 'screen', 'subversion', 'unzip', 'zip', 'zsh', 'libzmq3-dev', 'ruby-dev', 'default-jdk', 'python-setuptools']
    force: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Update all packages to the latest version
  apt: update_cache=yes cache_valid_time=86400 upgrade=safe
  become: yes

- name: autoclean unused apt packages.
  apt: update_cache=yes cache_valid_time=86400 autoremove=true
  become: yes
