# Run this before other pip modules.
# pip installed with apt-get is not up-to-date.
- name: Install up-to-date pip
  become: yes
  pip: executable=pip3 name=pip state=latest

# Install other Python libraries as user.
- name: Install Python popular ML libraries.
  pip:
    state: latest
    extra_args: --user
    executable: pip3
    name:
    - jupyter
    - jupyterlab
    - matplotlib
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - tensorflow
    - keras
    - passlib
    - virtualenv
  