- name: Create .ssh directory
  file:
    path: ~/.ssh
    state: directory
    mode: 0700
# Although copy_module doc says dest is "Remote absolute path",
# `~/` looks working in my environment.
# https://docs.ansible.com/ansible/latest/modules/copy_module.html
# TODO(yunabe): Understand why it works.
- name: Copy a ssh private key for devenv
  copy:
    src: ~/.ssh/dev_id_ed25519
    dest: ~/.ssh/id_ed25519
    mode: 0600
- name: Copy a ssh public key for devenv
  copy:
    src: ~/.ssh/dev_id_ed25519.pub
    dest: ~/.ssh/id_ed25519.pub
    mode: 0644
