# Install the latest version of Go.
# https://github.com/golang/go/wiki/Ubuntu
- name: Register Go apt-repository
  apt_repository:
    repo: ppa:longsleep/golang-backports
    update_cache: yes
  become: yes
- name: Install Go
  apt:
    name: golang-go
    force: yes
    update_cache: yes
    cache_valid_time: 86400
  become: yes

# Install the latest version of docker on ubuntu.
# https://docs.docker.com/engine/installation/linux/ubuntu/
- name: Install Docker GPG key
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: 0EBFCD88
- name: Register docker apt-repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    update_cache: yes
- name: Install docker-ce
  become: yes
  apt:
    name: docker-ce
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    force: yes
    update_cache: yes
    cache_valid_time: 3600
- name: Add {{ user }} to docker group
  become: yes
  user:
    name: "{{ user }}"
    shell: /bin/zsh
    append: yes
    groups: docker

# Install the latest Node.js
# https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
- name: Install NodeSource GPG key
  become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    id: 68576280
# TODO(yunabe): Remove these two rules once node_13.x are removed from all environments.
- name: Remove node_13.x apt-repository
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/node_13.x {{ansible_lsb.codename}} main
    update_cache: yes
    state: absent
- name: Remove node_13.x NodeSource deb-src apt-repository
  become: yes
  apt_repository:
    repo: deb-src https://deb.nodesource.com/node_13.x {{ansible_lsb.codename}} main
    update_cache: yes
    state: absent
- name: Register NodeSource apt-repository
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/node_16.x {{ansible_lsb.codename}} main
    update_cache: yes
- name: Register NodeSource deb-src apt-repository
  become: yes
  apt_repository:
    repo: deb-src https://deb.nodesource.com/node_16.x {{ansible_lsb.codename}} main
    update_cache: yes
- name: Install the latest Node.js
  become: yes
  apt:
    name: nodejs
    force: yes
    update_cache: yes
    cache_valid_time: 86400

# Install the latest yarn
# https://yarnpkg.com/en/docs/install#debian-stable
- name: Install Yarn GPG key
  become: yes
  apt_key:
    url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    id: 86E50310
- name: Register yarn apt-repository
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    update_cache: yes
- name: Install yarn
  become: yes
  apt:
    name: yarn
    force: yes
    update_cache: yes
    cache_valid_time: 86400

# Install bazel
# https://docs.bazel.build/versions/master/install-ubuntu.html#install-on-ubuntu
- name: Install Bazel APT Key
  become: yes
  apt_key:
    url: "https://bazel.build/bazel-release.pub.gpg"
- name: Register Bazel apt-repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8
    update_cache: yes
- name: Install Bazel
  become: yes
  apt:
    name: bazel
    force: yes
    update_cache: yes
    cache_valid_time: 86400

# Install Google Cloud SDK
# https://cloud.google.com/sdk/docs/install?hl=en#deb
- name: Install Cloud SDK GPG key
  become: yes
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
- name: Register Cloud SDK apt-repository
  become: yes
  apt_repository:
    repo: deb http://packages.cloud.google.com/apt cloud-sdk main
    update_cache: yes
- name: Install Google Cloud SDK
  become: yes
  apt:
    name: 'google-cloud-sdk'
    name: "{{ item }}"
    force: yes
    update_cache: yes
    cache_valid_time: 86400
